language: python
branches:
  only:
    - source

install:
  - rsync -v
# cache: pip
# install:
#   - pip install pelican markdown pymdown-extensions
# script:
#   - pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info
#   - rsync -rzP ivicel.info $user@$host::blog
