language: python
branches:
  only:
    - master
install:
  - pip install pelican
script:
  - make publish
before_install:
  - openssl aes-256-cbc -K $encrypted_59ce41fee125_key -iv $encrypted_59ce41fee125_iv
    -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
