language: python
branches:
  only:
    - master
cache: pip
before_install:
  - openssl aes-256-cbc -K $encrypted_59ce41fee125_key -iv $encrypted_59ce41fee125_iv
    -in deploy_key.enc -out ~/.ssh/deploy_key -d
  - openssl aes-256-cbc -K $encrypted_59ce41fee125_key -iv $encrypted_59ce41fee125_iv
    -in passwd.enc -out passwd -d
  - chmod 600 ~/.ssh/deploy_key
install:
  - pip install pelican
script:
  - pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info
after_success:
  - rsync -avzP --password-file=passwd ivicel.info $user@$host::/
