language: python
branches:
  only:
  - source
cache: pip
install:
- pip install pelican markdown pymdown-extensions
script:
- pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info
- rsync -rzogP ivicel.info/* $target --password-file=deploy_key
before_install:
- openssl aes-256-cbc -K $encrypted_59ce41fee125_key -iv $encrypted_59ce41fee125_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 0600 deploy_key
