language: python
branches:
  only:
    - master
cache: pip
install:
  - pip install pelican markdown pymdown-extensions
script:
  - make publish
  - rsync -rvzogP --chown=$user:$user ivicel.info/ $user@$host::blog
