language: python
branches:
  only:
  - source
cache: pip
install:
- pip install pelican markdown pymdown-extensions
script:
- pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info
- rsync -rzogP ivicel.info/* $target
addons:
  ssh_known_hosts: 35.243.84.241
before_install:
- openssl aes-256-cbc -K $encrypted_59ce41fee125_key -iv $encrypted_59ce41fee125_iv
  -in deploy_rsa.enc -out /tmp/deploy_key.pub -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key.pub
- ssh-add /tmp/deploy_key.pub
