language: python
branches:
  only:
    - master
cache: pip
install:
  - pip install pelican
script:
  - pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info
after_success:
  - rsync -avzP ivicel.info $user@$host::blog
