name: Build blog
on:
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@source

      - name: Setup Python
        uses: actions/setup-python@v1.2.0
        with:
          python-version: 3.7

      # Runs a single command using the runners shell
      - name: Install required package and build
        run: |
          pip install pelican markdown pymdown-extensions
          pelican content -s publishconf.py -t themes/clean-blog -o ivicel.info

      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ${{ secrets.SOURCE }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
